baseurl = "https://eqrion.net/"
locale = "en-us"
title = "Ryan Hunt's Blog"

[params]
description = "Ryan Hunt's blog. Working on the WebAssembly engine and standards at Mozilla."
author = "Ryan Hunt"

[permalinks]
post = "/:slug/"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false
